### ISSUE TITLE
httpbody-chunked write blocking

### ISSUE THREAD

**Issue by Ignorant-lxf** [FlowerLab/sorbifolia#76]
https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L14, I can't understand why the type of Data and Header are chan []byte?

When I want to write,there will be blocking https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L78

Hope to get your answer @Aoang

**Comment by Aoang** [comment]
Chunked transfers may be used to return multiple results that cannot be returned immediately.

- When using `Chunked` to decode the `Body` in Request, `<-Chunked.Data`, `<-Chunked.Header` receives data in real time.
- When using `Chunked` to encode the `Body` in Response, `Chunked.Data<-`, `Chunked.Header<-` send data in real time.

Closing Chunked.Data, Chunked.Header means the transfer is complete.

> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding
> https://zh.m.wikipedia.org/zh/%E5%88%86%E5%9D%97%E4%BC%A0%E8%BE%93%E7%BC%96%E7%A0%81

**Comment by Ignorant-lxf** [comment]
There are some bugs:

- Responder write data by `Chunked.Dada<-`.Requester read data by `<-Chunked.Data`.It's mean that they use the same chunked. https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L24 and https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L96 . 
But the mode is conflicting,maybe use `ModeReadWrite`?
- https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L101 
```
chunked := AcquireChunked()
var p []byte
chunked.Read(p)
```
Maybe `len(p)` and  `n` are equals 0 forever?

- https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L106
If `len(p)==0` ,it's error to use copy. 
`Copy returns the number of elements copied, which will be the minimum of len(src) and len(dst).`
It's failed to circular replicate unless p is enough large.

How do you think @Aoang

**Comment by Aoang** [comment]
Regarding the length of `p`, it can be zero, but it will not be zero forever, unless the peer implementation is wrong.

See also: 
> https://github.com/golang/go/blob/go1.19.5/src/io/io.go#L55-L85
> https://github.com/golang/go/blob/go1.19.5/src/io/io.go#L426-L452

**Comment by Aoang** [comment]
len(p) won't be zero in https://github.com/FlowerLab/sorbifolia/blob/dff239b4acdf3d04874f3feabeca9f0b22aca83b/http/httpbody/chunked.go#L106 

see https://github.com/FlowerLab/sorbifolia/blob/dff239b4acdf3d04874f3feabeca9f0b22aca83b/http/httpbody/chunked.go#L102

**Comment by Aoang** [comment]
> * Responder write data by `Chunked.Dada<-`.Requester read data by `<-Chunked.Data`.It's mean that they use the same chunked. https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L24 and https://github.com/FlowerLab/sorbifolia/blob/http-no-arena/http/httpbody/chunked.go#L96 .
>   But the mode is conflicting,maybe use `ModeReadWrite`?

When we need to send Response, `net.Conn` reads data, we don't use `Chunked.Write` to write data, but `Chunked.Data`, `Chunked.Header`.
When we need to receive Request, read data from `net.Conn`, we don't use `Chunked.Read` to read data, but read from `Chunked.Data`, `Chunked.Header`.
In other cases, too.
